/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_grapjeje_nativechunks_NativeChunkGenerator */

#ifndef _Included_nl_grapjeje_nativechunks_NativeChunkGenerator
#define _Included_nl_grapjeje_nativechunks_NativeChunkGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_grapjeje_nativechunks_NativeChunkGenerator
 * Method:    generateChunkNative
 * Signature: (IIJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_grapjeje_nativechunks_NativeChunkGenerator_generateChunkNative
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     nl_grapjeje_nativechunks_NativeChunkGenerator
 * Method:    getMaterialName
 * Signature: (B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_grapjeje_nativechunks_NativeChunkGenerator_getMaterialName
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
